SELECT
    YEAR(o.SALES_DATE) YEAR,
    MONTH(o.SALES_DATE) MONTH,
    u.GENDER,
    COUNT(DISTINCT u.USER_ID) USERS
FROM USER_INFO u
INNER JOIN ONLINE_SALE o
ON u.USER_ID = o.USER_ID
GROUP BY YEAR, MONTH, u.GENDER
HAVING u.GENDER IS NOT NULL
ORDER BY YEAR, MONTH, u.GENDER